sudo: required
services:
  - docker
before_install:
  - docker build -t ashok-mane/react-test -f ./client/Dockerfile.dev ./client

after_success:
  - docker build -t ashok-mane/multi-client ./client
  - docker build -t ashok-mane/multi-server ./server
  - docker build -t ashok-mane/multi-nginx ./nginx
  - docker build -t ashok-mane/multi-worker ./worker
# login to docker client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#  push above images to docker hub  
  - docker push ashok-mane/multi-client
  - docker push ashok-mane/multi-server
  - docker push ashok-mane/multi-nginx
  - docker push ashok-mane/multi-worker  